version: '3'

services:
  code-server:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    image: codercom/code-server
    volumes:
      - ${CODESERVER_DATA_PATH}:/home/coder/project
      - ${CODESERVER_SSL_PATH}:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: 8080
      SSLCERT: ${CODESERVER_SSL_CERTIFICATE}
      SSLKEY: ${CODESERVER_SSL_KEY}

networks:
    default:
       external:
         name: ${NETWORK}
